[tool.poetry]
name = "compotes"
version = "2.0.0"
description = "Track debts & pools"
authors = ["Guilhem Saurel <guilhem.saurel@laas.fr>"]
license = "BSD-2-Clause"
readme = "README.md"
homepage = "https://github.com/nim65s/compotes"

[tool.poetry.urls]
"changelog" = "https://github.com/nim65s/compotes/blob/main/CHANGELOG.md"

[tool.poetry.dependencies]
python = "^3.10"
django-filter = "^22.1"
django-tables2 = "^2.4.1"
dmdm = "^2.0.3"
ipython = "^8.11.0"
ndh = "^5.11.3"
yeouia = "^4.0.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
black = "^22.3.0"
coverage = "^5.5"
flake8 = "^3.9.2"
isort = "^5.12.0"
pre-commit = "^2.11.1"
pydocstyle = "^6.0.0"
safety = "^2.2.0"

[tool.poetry.group.prod]
optional = true

[tool.poetry.group.prod.dependencies]
gunicorn = "^20.1.0"
psycopg2 = "^2.9.5"

[tool.isort]
profile = "black"
known_django = "django"
sections = "FUTURE,STDLIB,DJANGO,THIRDPARTY,FIRSTPARTY,LOCALFOLDER"

[tool.pydocstyle]
match_dir = "(?=[^\\.])(?!migrations).*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
