[tool.poetry]
name = "compotes"
version = "1.0.1"
description = "Track debts & pools"
authors = ["Guilhem Saurel <guilhem.saurel@laas.fr>"]
license = "BSD-2-Clause"

[tool.poetry.dependencies]
python = "^3.9"
ndh = "^5.7.4"
dmdm = "^1.4.5"
django-tables2 = "^2.4.1"
django-yeouia = "^2.0.0"
django-filter = "^22.1"

[tool.poetry.dev-dependencies]
coverage = "^5.5"
black = "^22.3.0"
#django-stubs = "^1.7.0"
flake8 = "^3.9.2"
#mypy = "^0.812"
pre-commit = "^2.11.1"
pydocstyle = "^6.0.0"
safety = "^1.10.3"
ipython = "^8.0.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
