# Generated by Django 4.0.3 on 2022-03-13 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compotes", "0003_alter_debt_options_alter_part_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="debt",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
        migrations.AlterField(
            model_name="pool",
            name="created",
            field=models.DateTimeField(auto_now_add=True, verbose_name="created"),
        ),
        migrations.AlterField(
            model_name="pool",
            name="name",
            field=models.CharField(max_length=200, unique=True, verbose_name="name"),
        ),
        migrations.AlterField(
            model_name="pool",
            name="updated",
            field=models.DateTimeField(auto_now=True, verbose_name="updated"),
        ),
    ]
