# Generated by Django 4.0.3 on 2022-03-13 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compotes', '0004_alter_debt_created_alter_debt_updated_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='part',
            unique_together=set(),
        ),
    ]
