# Generated by Django 4.0.3 on 2022-03-13 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compotes", "0005_alter_part_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="part",
            name="description",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="description"
            ),
        ),
    ]
