# Generated by Django 4.1 on 2022-08-29 20:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compotes", "0006_part_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="creditor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creditor",
            ),
        ),
        migrations.AlterField(
            model_name="debt",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="debt",
            name="part_value",
            field=models.FloatField(default=0, verbose_name="Part value"),
        ),
        migrations.AlterField(
            model_name="debt",
            name="scribe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Scribe",
            ),
        ),
        migrations.AlterField(
            model_name="debt",
            name="value",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Value"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="debitor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Debitor",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="debt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="compotes.debt",
                verbose_name="Debt",
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="description",
            field=models.CharField(
                blank=True, max_length=1000, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="part",
            name="part",
            field=models.FloatField(default=1, verbose_name="Part"),
        ),
        migrations.AlterField(
            model_name="part",
            name="value",
            field=models.FloatField(default=0, verbose_name="Value"),
        ),
        migrations.AlterField(
            model_name="pool",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="pool",
            name="organiser",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Organiser",
            ),
        ),
        migrations.AlterField(
            model_name="pool",
            name="ratio",
            field=models.FloatField(default=0, verbose_name="Ratio"),
        ),
        migrations.AlterField(
            model_name="pool",
            name="value",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Value"
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="maxi",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Maxi"
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="participant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Participant",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="pool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="compotes.pool",
                verbose_name="Pool",
            ),
        ),
        migrations.AlterField(
            model_name="share",
            name="value",
            field=models.FloatField(default=0, verbose_name="Value"),
        ),
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=8, verbose_name="Balance"
            ),
        ),
    ]
