# Generated by Django 4.1 on 2022-08-29 20:53

from django.db import migrations, models
import django.utils.timezone


def set_initial_date(apps, schema_editor):
    Debt = apps.get_model("compotes", "Debt")
    Debt.objects.update(date=F("created"))


class Migration(migrations.Migration):

    dependencies = [
        ("compotes", "0008_debt_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="debt",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.RunPython(set_initial_date),
    ]
