# Generated by Django 4.1 on 2022-08-29 21:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("compotes", "0009_debt_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="debt",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Date"
            ),
        ),
    ]
