# Generated by Django 4.1 on 2022-09-03 11:26

import autoslug.fields
from autoslug.utils import slugify
from django.db import migrations


def set_initial_user_slug(apps, schema_editor):
    User = apps.get_model("compotes", "User")
    for user in User.objects.all():
        user.slug = slugify(user.username)
        user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("compotes", "0010_alter_debt_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                default="CHANGE-ME", editable=False, populate_from="username"
            ),
            preserve_default=False,
        ),
        migrations.RunPython(set_initial_user_slug),
    ]
