# Generated by Django 4.1 on 2022-09-03 11:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("compotes", "0011_user_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from="username", unique=True
            ),
        ),
    ]
