# Generated by Django 4.1 on 2022-09-05 12:57

from json import loads

from django.db import migrations
from django.core.serializers import serialize


def to_json(inst):
    return loads(serialize("json", [inst]))[0]


def log_scribe(apps, schema_editor):
    Debt = apps.get_model("compotes", "Debt")
    Part = apps.get_model("compotes", "Part")
    Action = apps.get_model("actions", "Action")
    for debt in Debt.objects.all():
        Action.objects.create(user=debt.scribe, act="C", json=to_json(debt))
    for part in Part.objects.all():
        Action.objects.create(user=part.debt.scribe, act="C", json=to_json(part))


class Migration(migrations.Migration):

    dependencies = [
        ("compotes", "0012_alter_user_slug"),
        ("actions", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(log_scribe),
    ]
