# Generated by Django 4.1.2 on 2022-10-10 23:50

from json import loads

from django.core.serializers import serialize
from django.db import migrations


def to_json(inst):
    return loads(serialize("json", [inst]))[0]


def log_orga(apps, schema_editor):
    Pool = apps.get_model("compotes", "Pool")
    Share = apps.get_model("compotes", "Share")
    Action = apps.get_model("actions", "Action")
    for pool in Pool.objects.all():
        Action.objects.create(user=pool.organiser, act="C", json=to_json(pool))
    for share in Share.objects.all():
        Action.objects.create(user=share.participant, act="C", json=to_json(share))


class Migration(migrations.Migration):

    dependencies = [
        ("compotes", "0014_remove_debt_scribe"),
    ]

    operations = [
        migrations.RunPython(log_orga),
    ]
