# Generated by Django 4.1.2 on 2022-11-10 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("compotes", "0015_log_orga"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="respo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
