name: Lints
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: poetry
      - name: setup
        run: poetry install --with dev
      - run: poetry run black .
      - run: poetry run ruff .
      #- run: poetry run mypy .
      - run: poetry run safety check
      - run: poetry run poetry check
